### ISSUE TITLE
SharedStreets installation via docker fails (403 error at OSM)

### ISSUE THREAD

**Issue by karthikappy** [sharedstreets/sharedstreets-js#91]
I tried to install sharedstreets using the Dockerfile method, but I am getting a 403 error when running 
`docker build --tag shst-image .`

Here is the output from the command:
```
[+] Building 31.9s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 189B                                                                               0.1s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/node:11                                                        10.7s
 => CACHED [1/2] FROM docker.io/library/node:11@sha256:67ca28addce8ae818b144114a9376a6603aba09069b7313618d37b3858  0.0s
 => ERROR [2/2] RUN npm install -g sharedstreets                                                                  21.1s
------
 > [2/2] RUN npm install -g sharedstreets:
#5 12.51 npm WARN deprecated node-pre-gyp@0.12.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
#5 19.73 /home/node/.npm-global/bin/shst -> /home/node/.npm-global/lib/node_modules/sharedstreets/bin/run
#5 19.76
#5 19.76 > leveldown@5.6.0 install /home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/leveldown
#5 19.76 > node-gyp-build
#5 19.76
#5 19.90
#5 19.90 > osrm@5.24.0 install /home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/osrm
#5 19.90 > node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh
#5 19.90
#5 20.05 node-pre-gyp WARN Using needle for node-pre-gyp https download
#5 20.24 node-pre-gyp ERR! install error
#5 20.24 node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.24.0/Release/node-v67-linux-x64.tar.gz
#5 20.24 node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/node-pre-gyp/lib/install.js:149:27)
#5 20.24 node-pre-gyp ERR! stack     at PassThrough.emit (events.js:198:15)
#5 20.24 node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/needle/lib/needle.js:508:9)
#5 20.24 node-pre-gyp ERR! stack     at Object.onceWrapper (events.js:281:20)
#5 20.24 node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
#5 20.24 node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
#5 20.24 node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
#5 20.24 node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:447:22)
#5 20.24 node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
#5 20.24 node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
#5 20.24 node-pre-gyp ERR! System Linux 5.4.72-microsoft-standard-WSL2
#5 20.24 node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
#5 20.24 node-pre-gyp ERR! cwd /home/node/.npm-global/lib/node_modules/sharedstreets/node_modules/osrm
#5 20.24 node-pre-gyp ERR! node -v v11.15.0
#5 20.24 node-pre-gyp ERR! node-pre-gyp -v v0.12.0
#5 20.24 node-pre-gyp ERR! not ok
#5 20.24 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.24.0/Release/node-v67-linux-x64.tar.gz
#5 20.30 Needs cmake to build from source
#5 21.01 npm ERR! code ELIFECYCLE
#5 21.01 npm ERR! errno 1
#5 21.01 npm ERR! osrm@5.24.0 install: `node-pre-gyp install --fallback-to-build=false || ./scripts/node_install.sh`
#5 21.01 npm ERR! Exit status 1
#5 21.01 npm ERR!
#5 21.01 npm ERR! Failed at the osrm@5.24.0 install script.
#5 21.01 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
#5 21.04
#5 21.04 npm ERR! A complete log of this run can be found in:
#5 21.04 npm ERR!     /home/node/.npm/_logs/2021-03-26T19_06_30_761Z-debug.log
------
executor failed running [/bin/sh -c npm install -g sharedstreets]: exit code: 1
```

**Comment by karthikappy** [comment]
I finally managed to fix this issue by changing the first line of the Dockerfile from:
```
FROM node:11
```
to
```
FROM node:10
```
It seems ```osrm``` is not available for Node JS v11 and above
